// @routes-hash d462cdf9b1051356068987303e7fce06
import { Express } from "express";

import route1 from "./routes/admin/orders";
import route2 from "./routes/admin/site";
import route3 from "./routes/admin/usage";
import route4 from "./routes/admin/users";
import route5 from "./routes/agents/clearMemory";
import route6 from "./routes/agents/getMemory";
import route7 from "./routes/artStyle/addArtStyle";
import route8 from "./routes/artStyle/editArtStyle";
import route9 from "./routes/artStyle/extractStylePrompt";
import route10 from "./routes/artStyle/getArtStyle";
import route11 from "./routes/assets/addAssets";
import route12 from "./routes/assets/addAudioAssets";
import route13 from "./routes/assets/batchDelete";
import route14 from "./routes/assets/batchGenerationData";
import route15 from "./routes/assets/delAssets";
import route16 from "./routes/assets/delImage";
import route17 from "./routes/assets/getAssetsApi";
import route18 from "./routes/assets/getImage";
import route19 from "./routes/assets/getMaterialData";
import route20 from "./routes/assets/pollingImageAssets";
import route21 from "./routes/assets/pollingPromptAssets";
import route22 from "./routes/assets/saveAssets";
import route23 from "./routes/assets/updateAssets";
import route24 from "./routes/assets/updateAudioAssets";
import route25 from "./routes/assets/uploadClip";
import route26 from "./routes/assetsGenerate/batchGenerateImageAssets";
import route27 from "./routes/assetsGenerate/batchPolishAssetsPrompt";
import route28 from "./routes/assetsGenerate/cancelGenerate";
import route29 from "./routes/assetsGenerate/generateAssets";
import route30 from "./routes/assetsGenerate/polishAssetsPrompt";
import route31 from "./routes/auth/register";
import route32 from "./routes/auth/userInfo";
import route33 from "./routes/billing/balance";
import route34 from "./routes/billing/estimate";
import route35 from "./routes/billing/recharge";
import route36 from "./routes/billing/recharge/list";
import route37 from "./routes/billing/usage";
import route38 from "./routes/billing/usage/summary";
import route39 from "./routes/common/getBigImage";
import route40 from "./routes/cornerScape/batchBindAudio";
import route41 from "./routes/cornerScape/getAllAssets";
import route42 from "./routes/cornerScape/pollingAudio";
import route43 from "./routes/cornerScape/updateAssetsAudio";
import route44 from "./routes/general/generalStatistics";
import route45 from "./routes/general/getSingleProject";
import route46 from "./routes/general/updateProject";
import route47 from "./routes/login/login";
import route48 from "./routes/modelSelect/getModelDetail";
import route49 from "./routes/modelSelect/getModelList";
import route50 from "./routes/novel/addNovel";
import route51 from "./routes/novel/batchDeleteNovel";
import route52 from "./routes/novel/delNovel";
import route53 from "./routes/novel/event/batchDeleteEvent";
import route54 from "./routes/novel/event/deletEvent";
import route55 from "./routes/novel/event/generateEvents";
import route56 from "./routes/novel/event/getEvent";
import route57 from "./routes/novel/getNovel";
import route58 from "./routes/novel/getNovelData";
import route59 from "./routes/novel/getNovelEventState";
import route60 from "./routes/novel/getNovelIndex";
import route61 from "./routes/novel/updateNovel";
import route62 from "./routes/other/deleteAllData";
import route63 from "./routes/other/getVersion";
import route64 from "./routes/production/assets/batchGenerateAssetsImage";
import route65 from "./routes/production/assets/deleteAssetsDireve";
import route66 from "./routes/production/assets/pollingImage";
import route67 from "./routes/production/assets/updateAssetsUrl";
import route68 from "./routes/production/editImage/generateFlowImage";
import route69 from "./routes/production/editImage/getImageDefaultModle";
import route70 from "./routes/production/editImage/getImageFlow";
import route71 from "./routes/production/editImage/saveImageFlow";
import route72 from "./routes/production/editImage/updateImageFlow";
import route73 from "./routes/production/editImage/uploadImage";
import route74 from "./routes/production/getFlowData";
import route75 from "./routes/production/getStoryboardData";
import route76 from "./routes/production/saveFlowData";
import route77 from "./routes/production/storyboard/addStoryboard";
import route78 from "./routes/production/storyboard/batchAddStoryboardInfo";
import route79 from "./routes/production/storyboard/batchDelete";
import route80 from "./routes/production/storyboard/batchGenerateImage";
import route81 from "./routes/production/storyboard/downPreviewImage";
import route82 from "./routes/production/storyboard/editStoryboardInfo";
import route83 from "./routes/production/storyboard/getStoryboardData";
import route84 from "./routes/production/storyboard/pollingImage";
import route85 from "./routes/production/storyboard/previewImage";
import route86 from "./routes/production/storyboard/removeFrame";
import route87 from "./routes/production/storyboard/updateStoryboardUrl";
import route88 from "./routes/production/workbench/addTrack";
import route89 from "./routes/production/workbench/batchGeneratePrompt";
import route90 from "./routes/production/workbench/batchGenerateVideo";
import route91 from "./routes/production/workbench/checkVideoPrompt";
import route92 from "./routes/production/workbench/checkVideoStateList";
import route93 from "./routes/production/workbench/deleteTrack";
import route94 from "./routes/production/workbench/delVideo";
import route95 from "./routes/production/workbench/generateVideo";
import route96 from "./routes/production/workbench/generateVideoPrompt";
import route97 from "./routes/production/workbench/getAudioBindAssetsList";
import route98 from "./routes/production/workbench/getFileUrl";
import route99 from "./routes/production/workbench/getGenerateData";
import route100 from "./routes/production/workbench/getVideoList";
import route101 from "./routes/production/workbench/selectVideo";
import route102 from "./routes/production/workbench/updateVideoDuration";
import route103 from "./routes/production/workbench/updateVideoPrompt";
import route104 from "./routes/project/addDirectorManual";
import route105 from "./routes/project/addProject";
import route106 from "./routes/project/addVisualManual";
import route107 from "./routes/project/deleteDirectorManual";
import route108 from "./routes/project/deleteVisualManual";
import route109 from "./routes/project/delProject";
import route110 from "./routes/project/editDirectorlManual";
import route111 from "./routes/project/editProject";
import route112 from "./routes/project/editVisualManual";
import route113 from "./routes/project/getModelDetails";
import route114 from "./routes/project/getProject";
import route115 from "./routes/project/getVisualManual";
import route116 from "./routes/project/queryDirectorManual";
import route117 from "./routes/project/visualManual";
import route118 from "./routes/script/addScript";
import route119 from "./routes/script/batchAddScript";
import route120 from "./routes/script/delScript";
import route121 from "./routes/script/exportScript";
import route122 from "./routes/script/extractAssets";
import route123 from "./routes/script/getAiRegex";
import route124 from "./routes/script/getScrptApi";
import route125 from "./routes/script/pollScriptAssets";
import route126 from "./routes/script/updateScript";
import route127 from "./routes/scriptAgent/getPlanData";
import route128 from "./routes/scriptAgent/setPlanData";
import route129 from "./routes/scriptAgent/updateData";
import route130 from "./routes/setting/about/checkUpdate";
import route131 from "./routes/setting/about/downloadApp";
import route132 from "./routes/setting/agentDeploy/agentSetKey";
import route133 from "./routes/setting/agentDeploy/deployAgentModel";
import route134 from "./routes/setting/agentDeploy/getAgentDeploy";
import route135 from "./routes/setting/agentDeploy/getAgentUseMode";
import route136 from "./routes/setting/agentDeploy/updateAgentModel";
import route137 from "./routes/setting/agentDeploy/updateUseMode";
import route138 from "./routes/setting/dbConfig/clearData";
import route139 from "./routes/setting/dbConfig/clearTable";
import route140 from "./routes/setting/dbConfig/dbInfo";
import route141 from "./routes/setting/dbConfig/exportData";
import route142 from "./routes/setting/dbConfig/importData";
import route143 from "./routes/setting/dev/getSwitchAiDevTool";
import route144 from "./routes/setting/dev/updateSwitchAiDevTool";
import route145 from "./routes/setting/fileManagement/openFolder";
import route146 from "./routes/setting/getTextModel";
import route147 from "./routes/setting/loginConfig/getUser";
import route148 from "./routes/setting/loginConfig/updateUserPwd";
import route149 from "./routes/setting/memoryConfig/delAllMemory";
import route150 from "./routes/setting/memoryConfig/getMemory";
import route151 from "./routes/setting/memoryConfig/sureMemory";
import route152 from "./routes/setting/modelMap/bindingPrompt";
import route153 from "./routes/setting/modelMap/deletePrompt";
import route154 from "./routes/setting/modelMap/getImageAndVideoModel";
import route155 from "./routes/setting/modelMap/getPromptList";
import route156 from "./routes/setting/modelMap/savePrompt";
import route157 from "./routes/setting/modelMap/updatePrompt";
import route158 from "./routes/setting/priceConfig";
import route159 from "./routes/setting/promptManage/getPrompt";
import route160 from "./routes/setting/promptManage/updatePrompt";
import route161 from "./routes/setting/skillManagement/getSkillContent";
import route162 from "./routes/setting/skillManagement/getSkillList";
import route163 from "./routes/setting/skillManagement/saveSkillContent";
import route164 from "./routes/setting/vendorConfig/addVendor";
import route165 from "./routes/setting/vendorConfig/addVendorModel";
import route166 from "./routes/setting/vendorConfig/deleteVendor";
import route167 from "./routes/setting/vendorConfig/delVendorModel";
import route168 from "./routes/setting/vendorConfig/enableVendor";
import route169 from "./routes/setting/vendorConfig/getCodeByLink";
import route170 from "./routes/setting/vendorConfig/getVendorList";
import route171 from "./routes/setting/vendorConfig/modelTest";
import route172 from "./routes/setting/vendorConfig/modelTest/imageTest";
import route173 from "./routes/setting/vendorConfig/modelTest/textTest";
import route174 from "./routes/setting/vendorConfig/modelTest/videoTest";
import route175 from "./routes/setting/vendorConfig/updateCode";
import route176 from "./routes/setting/vendorConfig/updateVendorInputs";
import route177 from "./routes/setting/vendorConfig/upVendorModel";
import route178 from "./routes/site/config";
import route179 from "./routes/task/getProject";
import route180 from "./routes/task/getTaskApi";
import route181 from "./routes/task/getTaskCategories";
import route182 from "./routes/task/taskDetails";
import route183 from "./routes/test/test";

export default async (app: Express) => {
  app.use("/api/admin/orders", route1);
  app.use("/api/admin/site", route2);
  app.use("/api/admin/usage", route3);
  app.use("/api/admin/users", route4);
  app.use("/api/agents/clearMemory", route5);
  app.use("/api/agents/getMemory", route6);
  app.use("/api/artStyle/addArtStyle", route7);
  app.use("/api/artStyle/editArtStyle", route8);
  app.use("/api/artStyle/extractStylePrompt", route9);
  app.use("/api/artStyle/getArtStyle", route10);
  app.use("/api/assets/addAssets", route11);
  app.use("/api/assets/addAudioAssets", route12);
  app.use("/api/assets/batchDelete", route13);
  app.use("/api/assets/batchGenerationData", route14);
  app.use("/api/assets/delAssets", route15);
  app.use("/api/assets/delImage", route16);
  app.use("/api/assets/getAssetsApi", route17);
  app.use("/api/assets/getImage", route18);
  app.use("/api/assets/getMaterialData", route19);
  app.use("/api/assets/pollingImageAssets", route20);
  app.use("/api/assets/pollingPromptAssets", route21);
  app.use("/api/assets/saveAssets", route22);
  app.use("/api/assets/updateAssets", route23);
  app.use("/api/assets/updateAudioAssets", route24);
  app.use("/api/assets/uploadClip", route25);
  app.use("/api/assetsGenerate/batchGenerateImageAssets", route26);
  app.use("/api/assetsGenerate/batchPolishAssetsPrompt", route27);
  app.use("/api/assetsGenerate/cancelGenerate", route28);
  app.use("/api/assetsGenerate/generateAssets", route29);
  app.use("/api/assetsGenerate/polishAssetsPrompt", route30);
  app.use("/api/auth/register", route31);
  app.use("/api/auth/userInfo", route32);
  app.use("/api/billing/balance", route33);
  app.use("/api/billing/estimate", route34);
  app.use("/api/billing/recharge", route35);
  app.use("/api/billing/recharge/list", route36);
  app.use("/api/billing/usage", route37);
  app.use("/api/billing/usage/summary", route38);
  app.use("/api/common/getBigImage", route39);
  app.use("/api/cornerScape/batchBindAudio", route40);
  app.use("/api/cornerScape/getAllAssets", route41);
  app.use("/api/cornerScape/pollingAudio", route42);
  app.use("/api/cornerScape/updateAssetsAudio", route43);
  app.use("/api/general/generalStatistics", route44);
  app.use("/api/general/getSingleProject", route45);
  app.use("/api/general/updateProject", route46);
  app.use("/api/login/login", route47);
  app.use("/api/modelSelect/getModelDetail", route48);
  app.use("/api/modelSelect/getModelList", route49);
  app.use("/api/novel/addNovel", route50);
  app.use("/api/novel/batchDeleteNovel", route51);
  app.use("/api/novel/delNovel", route52);
  app.use("/api/novel/event/batchDeleteEvent", route53);
  app.use("/api/novel/event/deletEvent", route54);
  app.use("/api/novel/event/generateEvents", route55);
  app.use("/api/novel/event/getEvent", route56);
  app.use("/api/novel/getNovel", route57);
  app.use("/api/novel/getNovelData", route58);
  app.use("/api/novel/getNovelEventState", route59);
  app.use("/api/novel/getNovelIndex", route60);
  app.use("/api/novel/updateNovel", route61);
  app.use("/api/other/deleteAllData", route62);
  app.use("/api/other/getVersion", route63);
  app.use("/api/production/assets/batchGenerateAssetsImage", route64);
  app.use("/api/production/assets/deleteAssetsDireve", route65);
  app.use("/api/production/assets/pollingImage", route66);
  app.use("/api/production/assets/updateAssetsUrl", route67);
  app.use("/api/production/editImage/generateFlowImage", route68);
  app.use("/api/production/editImage/getImageDefaultModle", route69);
  app.use("/api/production/editImage/getImageFlow", route70);
  app.use("/api/production/editImage/saveImageFlow", route71);
  app.use("/api/production/editImage/updateImageFlow", route72);
  app.use("/api/production/editImage/uploadImage", route73);
  app.use("/api/production/getFlowData", route74);
  app.use("/api/production/getStoryboardData", route75);
  app.use("/api/production/saveFlowData", route76);
  app.use("/api/production/storyboard/addStoryboard", route77);
  app.use("/api/production/storyboard/batchAddStoryboardInfo", route78);
  app.use("/api/production/storyboard/batchDelete", route79);
  app.use("/api/production/storyboard/batchGenerateImage", route80);
  app.use("/api/production/storyboard/downPreviewImage", route81);
  app.use("/api/production/storyboard/editStoryboardInfo", route82);
  app.use("/api/production/storyboard/getStoryboardData", route83);
  app.use("/api/production/storyboard/pollingImage", route84);
  app.use("/api/production/storyboard/previewImage", route85);
  app.use("/api/production/storyboard/removeFrame", route86);
  app.use("/api/production/storyboard/updateStoryboardUrl", route87);
  app.use("/api/production/workbench/addTrack", route88);
  app.use("/api/production/workbench/batchGeneratePrompt", route89);
  app.use("/api/production/workbench/batchGenerateVideo", route90);
  app.use("/api/production/workbench/checkVideoPrompt", route91);
  app.use("/api/production/workbench/checkVideoStateList", route92);
  app.use("/api/production/workbench/deleteTrack", route93);
  app.use("/api/production/workbench/delVideo", route94);
  app.use("/api/production/workbench/generateVideo", route95);
  app.use("/api/production/workbench/generateVideoPrompt", route96);
  app.use("/api/production/workbench/getAudioBindAssetsList", route97);
  app.use("/api/production/workbench/getFileUrl", route98);
  app.use("/api/production/workbench/getGenerateData", route99);
  app.use("/api/production/workbench/getVideoList", route100);
  app.use("/api/production/workbench/selectVideo", route101);
  app.use("/api/production/workbench/updateVideoDuration", route102);
  app.use("/api/production/workbench/updateVideoPrompt", route103);
  app.use("/api/project/addDirectorManual", route104);
  app.use("/api/project/addProject", route105);
  app.use("/api/project/addVisualManual", route106);
  app.use("/api/project/deleteDirectorManual", route107);
  app.use("/api/project/deleteVisualManual", route108);
  app.use("/api/project/delProject", route109);
  app.use("/api/project/editDirectorlManual", route110);
  app.use("/api/project/editProject", route111);
  app.use("/api/project/editVisualManual", route112);
  app.use("/api/project/getModelDetails", route113);
  app.use("/api/project/getProject", route114);
  app.use("/api/project/getVisualManual", route115);
  app.use("/api/project/queryDirectorManual", route116);
  app.use("/api/project/visualManual", route117);
  app.use("/api/script/addScript", route118);
  app.use("/api/script/batchAddScript", route119);
  app.use("/api/script/delScript", route120);
  app.use("/api/script/exportScript", route121);
  app.use("/api/script/extractAssets", route122);
  app.use("/api/script/getAiRegex", route123);
  app.use("/api/script/getScrptApi", route124);
  app.use("/api/script/pollScriptAssets", route125);
  app.use("/api/script/updateScript", route126);
  app.use("/api/scriptAgent/getPlanData", route127);
  app.use("/api/scriptAgent/setPlanData", route128);
  app.use("/api/scriptAgent/updateData", route129);
  app.use("/api/setting/about/checkUpdate", route130);
  app.use("/api/setting/about/downloadApp", route131);
  app.use("/api/setting/agentDeploy/agentSetKey", route132);
  app.use("/api/setting/agentDeploy/deployAgentModel", route133);
  app.use("/api/setting/agentDeploy/getAgentDeploy", route134);
  app.use("/api/setting/agentDeploy/getAgentUseMode", route135);
  app.use("/api/setting/agentDeploy/updateAgentModel", route136);
  app.use("/api/setting/agentDeploy/updateUseMode", route137);
  app.use("/api/setting/dbConfig/clearData", route138);
  app.use("/api/setting/dbConfig/clearTable", route139);
  app.use("/api/setting/dbConfig/dbInfo", route140);
  app.use("/api/setting/dbConfig/exportData", route141);
  app.use("/api/setting/dbConfig/importData", route142);
  app.use("/api/setting/dev/getSwitchAiDevTool", route143);
  app.use("/api/setting/dev/updateSwitchAiDevTool", route144);
  app.use("/api/setting/fileManagement/openFolder", route145);
  app.use("/api/setting/getTextModel", route146);
  app.use("/api/setting/loginConfig/getUser", route147);
  app.use("/api/setting/loginConfig/updateUserPwd", route148);
  app.use("/api/setting/memoryConfig/delAllMemory", route149);
  app.use("/api/setting/memoryConfig/getMemory", route150);
  app.use("/api/setting/memoryConfig/sureMemory", route151);
  app.use("/api/setting/modelMap/bindingPrompt", route152);
  app.use("/api/setting/modelMap/deletePrompt", route153);
  app.use("/api/setting/modelMap/getImageAndVideoModel", route154);
  app.use("/api/setting/modelMap/getPromptList", route155);
  app.use("/api/setting/modelMap/savePrompt", route156);
  app.use("/api/setting/modelMap/updatePrompt", route157);
  app.use("/api/setting/priceConfig", route158);
  app.use("/api/setting/promptManage/getPrompt", route159);
  app.use("/api/setting/promptManage/updatePrompt", route160);
  app.use("/api/setting/skillManagement/getSkillContent", route161);
  app.use("/api/setting/skillManagement/getSkillList", route162);
  app.use("/api/setting/skillManagement/saveSkillContent", route163);
  app.use("/api/setting/vendorConfig/addVendor", route164);
  app.use("/api/setting/vendorConfig/addVendorModel", route165);
  app.use("/api/setting/vendorConfig/deleteVendor", route166);
  app.use("/api/setting/vendorConfig/delVendorModel", route167);
  app.use("/api/setting/vendorConfig/enableVendor", route168);
  app.use("/api/setting/vendorConfig/getCodeByLink", route169);
  app.use("/api/setting/vendorConfig/getVendorList", route170);
  app.use("/api/setting/vendorConfig/modelTest", route171);
  app.use("/api/setting/vendorConfig/modelTest/imageTest", route172);
  app.use("/api/setting/vendorConfig/modelTest/textTest", route173);
  app.use("/api/setting/vendorConfig/modelTest/videoTest", route174);
  app.use("/api/setting/vendorConfig/updateCode", route175);
  app.use("/api/setting/vendorConfig/updateVendorInputs", route176);
  app.use("/api/setting/vendorConfig/upVendorModel", route177);
  app.use("/api/site/config", route178);
  app.use("/api/task/getProject", route179);
  app.use("/api/task/getTaskApi", route180);
  app.use("/api/task/getTaskCategories", route181);
  app.use("/api/task/taskDetails", route182);
  app.use("/api/test/test", route183);
}
